name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run unit tests
      run: |
        python -m pytest test_app.py
        
    - name: Build Docker image
      run: |
        docker build -t hivebox .
        
    - name: Start Docker container
      run: |
        docker run -d --name hivebox -p 5000:5000 hivebox
        sleep 10  # Wait for container to start
        
    - name: Test version endpoint
      run: |
        response=$(curl -s http://localhost:5000/version)
        expected='{"version":"v0.0.1"}'
        if [ "$response" = "$expected" ]; then
          echo "Version endpoint test passed"
        else
          echo "Version endpoint test failed"
          echo "Expected: $expected"
          echo "Got: $response"
          exit 1
        fi