name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run unit tests without Docker
      run: |
        python -m pytest test_app.py
        
    - name: Build Docker image
      run: |
        docker build -t hivebox .
        
    - name: Test Docker container
      run: |
        docker run -d --name hivebox -p 5000:5000 hivebox
        sleep 10  # Wait longer for container to start
        # Test if service is up
        curl --retry 5 --retry-delay 5 http://localhost:5000/version || exit 1